### ISSUE TITLE
component裡使用的usingComponents沒有被編譯

### ISSUE THREAD

**Issue by HenriettaSu** [JJJYY/import-weapp-component#2]
使用的是iview-weapp的組件，i-input之類的都沒有問題
但是在引入i-radio的時候提示沒有找到i-cell，i-cell是i-radio組件引入的，就沒有被編譯進去了
暫時用的解決方法是在項目頁面裡引入i-radio的同時引入i-cell，但之後類似情況應該挺多的，就不是很友好的樣子

**Comment by JJJYY** [comment]
可以在导入组件的时候增加对组件依赖的检测，谢谢反馈

**Comment by JJJYY** [comment]
@HenriettaSu ，已经修复了，更新试下

**Comment by HenriettaSu** [comment]
感謝那麼迅速的跟進

我重新安裝嘗試了一下，i-cell還是沒有被編譯，我需要額外配置些什麼嗎？

目前版本：4.5.2
