### ISSUE TITLE
component裡使用的usingComponents還是沒有被編譯

### ISSUE THREAD

**Issue by HenriettaSu** [JJJYY/import-weapp-component#3]
你好，我重新安裝嘗試了一下，組件的依賴還是沒有被編譯

版本是4.5.2

我是需要額外配置什麼嗎？

謝謝

**Comment by JJJYY** [comment]
版本对的，方便的话把page和component里面的usingComponents发下吧，谢谢

**Comment by HenriettaSu** [comment]
path我忽略不寫

page:
`usingComponents: {
    'i-modal': '...'
}`

component:
`usingComponents: {
    'i-grid': '...',
    'i-grid-item': '...',
    'i-button': '...',
    'i-icon': '...'
}`

謝謝

**Comment by JJJYY** [comment]
`page`的`usingComponents: { 'i-modal': '...' }`没有具体路径么，没有具体路径我没办法看出来哪的问题

**Comment by HenriettaSu** [comment]
因為公司網絡環境限制，只能手打。還想偷懶一下www

`usingComponents: { 'i-modal': './../../../components/iview/dist/modal/index' }`

iview的組件我放在src/components/下

**Comment by JJJYY** [comment]
@HenriettaSu 相对路径处理的不好，发了新版本@4.5.3，测试一下

**Comment by HenriettaSu** [comment]
@JJJYY 已經好了，非常感謝
